import 'dart:io';
import 'dart:typed_data';

import 'package:anx_reader/service/sync/annotation_audio_asset_sync.dart';
import 'package:crypto/crypto.dart';
import 'package:flutter_test/flutter_test.dart';

class MemoryAudioTransport implements AnnotationAudioAssetTransport {
  final Map<String, List<int>> objects = {};
  int uploads = 0;
  int downloads = 0;

  String _key(List<String> path) => path.join('/');

  @override
  Future<void> download(List<String> remotePath, String localPath) async {
    downloads++;
    await File(localPath).writeAsBytes(objects[_key(remotePath)]!);
  }

  @override
  Future<bool> exists(List<String> path) async =>
      objects.containsKey(_key(path));

  @override
  Future<void> upload(String localPath, List<String> remotePath) async {
    uploads++;
    objects[_key(remotePath)] = await File(localPath).readAsBytes();
  }
}

Map<String, Object?> metadata(List<int> bytes, {String name = 'asset.mp3'}) => {
      'assetRef': 'annotation-assets/audio/$name',
      'format': 'mp3',
      'mimeType': 'audio/mpeg',
      'byteLength': bytes.length,
      'sha256': sha256.convert(bytes).toString(),
    };

Map<String, dynamic> document(
  Map<String, Object?> audio, {
  bool deletedAnnotation = false,
  bool deletedAudio = false,
}) =>
    {
      'schemaVersion': 2,
      'book': {
        'fingerprintAlgorithm': 'md5',
        'fingerprint': '0123456789abcdef0123456789abcdef',
      },
      'annotations': [
        {
          'id': 'annotation-1',
          'motivation': 'selection',
          'createdAt': '2026-01-01T00:00:00.000Z',
          'updatedAt': '2026-01-01T00:00:00.000Z',
          if (deletedAnnotation) 'deletedAt': '2026-01-02T00:00:00.000Z',
          'target': {
            'selectedText': 'hello',
            'selectors': [
              {'type': 'epub-cfi', 'cfi': 'epubcfi(/6/2!/4/1:0)'}
            ],
          },
          'enrichments': [
            {
              'id': 'audio-1',
              'kind': 'audio',
              'providerId': 'openai-audio',
              'providerName': 'OpenAI Audio',
              'ipa': 'həˈloʊ',
              'voice': 'alloy',
              'model': 'gpt-4o-mini-tts',
              'audio': audio,
              'createdAt': '2026-01-01T00:00:00.000Z',
              'updatedAt': '2026-01-01T00:00:00.000Z',
              if (deletedAudio) 'deletedAt': '2026-01-02T00:00:00.000Z',
            }
          ],
        }
      ],
    };

void main() {
  late Directory directory;
  late AnnotationAudioAssetStore store;
  late MemoryAudioTransport transport;
  late AnnotationAudioAssetSyncService service;

  setUp(() async {
    directory = await Directory.systemTemp.createTemp('anx-audio-asset-');
    store = AnnotationAudioAssetStore(
      resolveLocalPath: (relative) => '${directory.path}/$relative',
    );
    transport = MemoryAudioTransport();
    service = AnnotationAudioAssetSyncService(
      transport: transport,
      remoteRoot: 'Lingua Reader',
      store: store,
    );
  });

  tearDown(() => directory.delete(recursive: true));

  test('persists verified generated bytes under the safe asset ref', () async {
    final bytes = Uint8List.fromList([1, 2, 3]);
    await store.persist(metadata(bytes), bytes);

    expect(
      await File('${directory.path}/annotation-assets/audio/asset.mp3')
          .readAsBytes(),
      bytes,
    );
    await expectLater(
      store.persist(metadata(bytes), Uint8List.fromList([9, 9, 9])),
      throwsA(isA<AnnotationAudioAssetIntegrityException>()),
    );
  });

  test('uploads local bytes to the shared WebDAV asset path', () async {
    final bytes = Uint8List.fromList([4, 5, 6]);
    final audio = metadata(bytes);
    await store.persist(audio, bytes);

    final result = await service.syncDocument(document(audio));

    expect(result.uploaded, 1);
    expect(
      transport.objects['Lingua Reader/annotation-assets/audio/asset.mp3'],
      bytes,
    );
  });

  test('downloads remote bytes atomically and verifies integrity', () async {
    final bytes = <int>[7, 8, 9];
    final audio = metadata(bytes);
    transport.objects['Lingua Reader/annotation-assets/audio/asset.mp3'] =
        bytes;

    final result = await service.syncDocument(document(audio));

    expect(result.downloaded, 1);
    expect(
      await File(store.pathFor('annotation-assets/audio/asset.mp3'))
          .readAsBytes(),
      bytes,
    );
    expect(
      await File('${store.pathFor('annotation-assets/audio/asset.mp3')}.part')
          .exists(),
      isFalse,
    );
  });

  test('rejects corrupt remote bytes and ignores tombstoned references',
      () async {
    final expected = <int>[10, 11, 12];
    final audio = metadata(expected);
    transport.objects['Lingua Reader/annotation-assets/audio/asset.mp3'] = [99];

    await expectLater(
      service.syncDocument(document(audio)),
      throwsA(isA<AnnotationAudioAssetIntegrityException>()),
    );
    expect(
      await File(store.pathFor(audio['assetRef']! as String)).exists(),
      isFalse,
    );

    transport.objects.clear();
    expect(
      (await service.syncDocument(document(audio, deletedAudio: true))).missing,
      0,
    );
    expect(
      (await service.syncDocument(document(audio, deletedAnnotation: true)))
          .missing,
      0,
    );
  });
}
